### ISSUE TITLE
Cannot create entity with more than 3 components

### ISSUE THREAD

**Issue by justgook** [Seurimas/slime#1]
I would like create entity for player in platformer game
So it needs components:
1. position (x,y)
2. Dimensions(width height,)
3. Velocity (vX vY)
4. Mass
5. Input state
6. PlayerFlag (who can, and who cannot harm)
7. Sprite
....
My suggestion is to refactor little bit way how you create spawn entities to some kind of pupelines like http://package.elm-lang.org/packages/NoRedInk/elm-decode-pipeline/latest

**Comment by justgook** [comment]
```
{-| Add Additional component to spawn Entity.
-}
spawnEntityWith : ( ComponentSpec a (EntitySet world), a ) -> ( EntitySet world, EntityID, EntityID ) -> ( EntitySet world, EntityID, EntityID )
spawnEntityWith ( { getter, setter }, a ) ( updatedSet, id, uid ) =
    let
        updatedComponents =
            getter updatedSet
                |> setComponent id a
    in
    ( setter updatedComponents updatedSet, id, uid )
```

usage: 
```
spawnPlayer : Component.Position -> Component.Dimension -> World -> World
spawnPlayer position dimension world =
    let
        ( newEntity, id, uid ) =
            Slime.spawnEntity World.positions world { a = position }
                |> Slime.spawnEntityWith ( World.velocities, { vx = 0, vy = 0 } )
                |> Slime.spawnEntityWith ( World.dimensions, dimension )
                |> Slime.spawnEntityWith ( World.controls, { x = 0, y = 0 } )
    in
    newEntity

```

**Comment by seurimas** [comment]
Are you looking for `forNewEntity` and `&=>`? Be sure you're on 2.1.0. It's got necessities like that.

To use your example, it would be:

    spawnPlayer : Component.Position -> Component.Dimension -> World -> World
    spawnPlayer position dimension world =
        let
            ( entityId, updatedWorld ) =
                Slime.forNewEntity world
                    &=> ( World.positions, position )
                    &=> ( World.velocities, { vx = 0, vy = 0 } )
                    &=> ( World.dimensions, dimension )
                    &=> ( World.controls, { x = 0, y = 0 } )
        in
            updatedWorld

Looking at the docs, I completely forgot `spawnEmpty`, `spawnEntity(2)`, and `spawnEntities(2)` even existed. 3.0.0 might remove them, since `forNewEntity` and `forNewEntities` are better.

**Comment by justgook** [comment]
tnx for info - would be nice see somethink like that in Docs..

**Comment by justgook** [comment]
thanks for help.. maybe would be nice reference to it from "spawnEntity" that this method is "better" (and exist)..

**Comment by justgook** [comment]
maybe there is something like `&=>` also for `Slime.stepEntities` - to not use
```
control : Time -> World -> World
control delta =
    Slime.stepEntities (Slime.entities2 World.controls World.velocities)(\({ a, b } as ent2) -> ent2)
```
but something like 
```
    Slime.stepEntities (Slime.forEntity world &=> World.controls &=> World.velocities)(\({x, y}, {vx, vy}) as ent2 -> ent2)
```

**Comment by seurimas** [comment]
The problem with that is you can't build tuples like that, I don't think. Unless they're secretly cons cells and I didn't notice. Even if they were, what would the type of `forEntity` be? The a/b/c notation is a serious disappointment, but it is less of an issue, since systems should rarely need to key on more than 2 or 3 components.  Still, I'll look into another method that might be nicer, as I've just had a bit of inspiration.

**Comment by Seurimas** [comment]
In any case, building steppers, while the a/b/c notation is a serious disappointment, is less of an issue, since systems should rarely need to key on more than 2 or 3 components.

**Comment by Seurimas** [comment]
I may explore an incomplete (max of 4 or 5) method for building entities in steppers as you describe.
